// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  AUTHENTICATION_KV: KVNamespace;
  FIREBASE_PROJECT_ID: 'sonuby-production';
  CURRENT_APP_VERSION: '1.7.1';
  ENVIRONMENT: 'development';
  BREVO_API_KEY: string;
  MAREA_TIDES_API_KEY: string;
  METEOBLUE_API_KEY: string;
  METEOBLUE_MAPS_API_KEY: string;
  METEOBLUE_SHARED_SECRET: string;
  SLACK_WEBHOOK_URL: string;
}
