#:schema node_modules/wrangler/config-schema.json

name = "sonuby-cloud-workers-v2"
account_id = "123"
workers_dev = false
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = [ "nodejs_compat" ]

[vars]
FIREBASE_PROJECT_ID = "sonuby-production"
CURRENT_APP_VERSION = "1.7.1"
ENVIRONMENT = "development"

[[kv_namespaces]]
binding = "AUTHENTICATION_KV"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[env.production.vars]
FIREBASE_PROJECT_ID = "sonuby-production"
CURRENT_APP_VERSION = "1.7.1"
ENVIRONMENT = "production"

[env.beta.vars]
FIREBASE_PROJECT_ID = "sonuby-beta"
CURRENT_APP_VERSION = "1.7.1"
ENVIRONMENT = "beta"

[env.staging.vars]
FIREBASE_PROJECT_ID = "sonuby-staging"
CURRENT_APP_VERSION = "1.7.1"
ENVIRONMENT = "staging"

[env.development.vars]
FIREBASE_PROJECT_ID = "sonuby-development"
CURRENT_APP_VERSION = "1.7.1"
ENVIRONMENT = "development"

[env.testing.vars]
FIREBASE_PROJECT_ID = "sonuby-development"
CURRENT_APP_VERSION = "1.7.1"
ENVIRONMENT = "testing"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
# [observability]
# enabled = true
